/**
 * BOM Export Utilities
 * 
 * Generates Bill of Materials in various formats:
 * - CSV (generic, compatible with Excel/Google Sheets)
 * - GOST-formatted CSV (Russian standard ЕСКД)
 */

export interface BomItem {
  designator: string;
  value: string;
  search_query: string;
  part_uuid?: string;
  block_name?: string;
  pins?: number;
}

/**
 * Generate a generic CSV BOM from circuit components.
 * Uses the LCSC search_query as the primary part identifier.
 */
export function generateBomCsv(components: BomItem[]): string {
  const headers = ['Designator', 'Value', 'Search Query', 'Part UUID', 'Block'];
  const rows = components.map(c => [
    c.designator,
    `"${(c.value || '').replace(/"/g, '""')}"`,
    `"${(c.search_query || c.value || '').replace(/"/g, '""')}"`,
    c.part_uuid || '',
    c.block_name || '',
  ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

/**
 * Generate a GOST-formatted BOM (ЕСКД / Unified System for Design Documentation).
 * 
 * GOST 2.701-2008 specifies the following columns:
 * - № (sequence number)
 * - Обозначение (designator reference)
 * - Наименование (name/designation)
 * - Кол. (quantity)
 * - Примечание (notes)
 * 
 * This is commonly used in Russian/CIS electronics manufacturing.
 */
export function generateGostBomCsv(components: BomItem[]): string {
  // Group components by value/search_query for quantity counting
  const groups = new Map<string, BomItem[]>();
  for (const c of components) {
    const key = `${c.value}|${c.search_query}`;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(c);
  }

  // GOST BOM header (in Russian, with English equivalents as comments)
  // Row 1: Document header
  const lines: string[] = [];
  lines.push('// GOST 2.701-2008 Bill of Materials');
  lines.push('// ЕСКД — Перечень элементов');
  lines.push('// Generated by EasyEDA AI Copilot');
  lines.push('');

  // Column headers (GOST standard)
  const headers = ['№', 'Обозначение', 'Наименование', 'Кол.', 'Примечание'];
  lines.push(headers.join(';'));

  let seq = 1;
  for (const [, items] of groups) {
    const first = items[0];
    const designators = items.map(i => i.designator).join(', ');
    const name = first.search_query || first.value;
    const count = items.length;

    // Map component type to Russian name
    const prefix = first.designator.replace(/\d+$/, '');
    let typeName = name;
    const typeMap: Record<string, string> = {
      'R': 'Резистор',
      'C': 'Конденсатор',
      'L': 'Индуктивность',
      'D': 'Диод',
      'LED': 'Светодиод',
      'Q': 'Транзистор',
      'U': 'Микросхема',
      'IC': 'Микросхема',
      'J': 'Разъем',
      'P': 'Разъем',
      'X': 'Кварцевый резонатор',
      'SW': 'Переключатель',
      'F': 'Предохранитель',
      'K': 'Реле',
    };
    if (typeMap[prefix]) {
      typeName = `${typeMap[prefix]} ${name}`;
    }

    const note = first.block_name || '';
    lines.push(`${seq};"${designators}";"${typeName}";${count};"${note}"`);
    seq++;
  }

  return lines.join('\n');
}

/**
 * Trigger a browser download of text content as a file.
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/csv;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
