/**
 * SPICE Netlist Export Utility
 * 
 * Converts circuit components into a SPICE-compatible netlist that can be
 * imported into LTSpice, ngspice, EasyEDA's built-in simulator, or KiCad's ngspice.
 * 
 * Supported analyses: .TRAN, .AC, .DC, .OP
 * Supported sources: DC, SIN, PULSE
 * 
 * Component mapping:
 *   R* -> Resistor
 *   C* -> Capacitor
 *   L* -> Inductor
 *   D* -> Diode (uses .model D)
 *   Q* -> BJT (uses .model NPN/PNP)
 *   M* -> MOSFET
 *   V* -> Voltage source
 *   I* -> Current source
 *   X* -> Subcircuit / Crystal
 *   U* -> IC (treated as subcircuit)
 */

export interface SpiceComponent {
  designator: string;
  value: string;
  pins: Array<{
    pin_number: number;
    name: string;
    signal_name: string;
  }>;
  block_name?: string;
}

export interface SpiceSource {
  signal_name: string;
  name: string;
  type: 'DC' | 'SIN' | 'PULSE';
  value: number;        // voltage/current value
  frequency?: number;   // for SIN
  offset?: number;      // for SIN
  fill?: number;        // for PULSE (duty cycle %)
}

export interface SpiceAnalysisOptions {
  type: 'transient' | 'ac' | 'dc' | 'op';
  // Transient
  step_time_ns?: number;
  end_time_ns?: number;
  // AC
  start_freq?: number;
  end_freq?: number;
  points_per_decade?: number;
  // DC sweep
  source_name?: string;
  start_value?: number;
  end_value?: number;
  step_value?: number;
}

/**
 * Convert signal_name to a valid SPICE node name.
 * SPICE node names cannot contain spaces or special chars.
 */
function toNode(signal: string): string {
  return signal
    .replace(/\s+/g, '_')
    .replace(/[^a-zA-Z0-9_+\-]/g, '_')
    .replace(/^\d/, 'N$&');  // SPICE nodes can't start with a digit
}

/**
 * Parse a component value into a numeric value + SPICE unit suffix.
 * e.g. "10k" -> "10k", "100nF" -> "100n", "10uH" -> "10u"
 */
function parseValue(value: string): string {
  if (!value) return '0';
  
  // Strip common unit suffixes and normalize
  let v = value.trim().toLowerCase();
  
  // Remove common unit suffixes
  v = v.replace(/(ohms?|omega|f(?:arad)?|h(?:enry)?|v(?:olts?)?|a(?:mps?)?)\b/, '');
  
  // Normalize SI prefixes
  const prefixMap: Record<string, string> = {
    'pico': 'p', 'nano': 'n', 'micro': 'u', 'milli': 'm',
    'kilo': 'k', 'mega': 'meg', 'giga': 'g',
  };
  for (const [full, short] of Object.entries(prefixMap)) {
    v = v.replace(new RegExp(full, 'g'), short);
  }
  
  // Extract number + prefix
  const match = v.match(/([0-9.]+)\s*([pnumkg]?(?:eg)?)?/);
  if (match) {
    return match[1] + (match[2] || '');
  }
  
  // Fallback: just return digits
  const digits = v.match(/[0-9.]+/);
  return digits ? digits[0] : '0';
}

/**
 * Get the SPICE model name for a diode.
 */
function getDiodeModel(value: string): string {
  const v = value.toLowerCase();
  if (v.includes('1n4148')) return 'D1N4148';
  if (v.includes('1n4007')) return 'D1N4007';
  if (v.includes('1n5819')) return 'D1N5819';
  if (v.includes('ss34')) return 'DSS34';
  if (v.includes('bat54')) return 'DBAT54';
  if (v.includes('zener') || v.includes('bzt52')) return 'DZENER';
  return 'D';
}

/**
 * Get the SPICE model name for a BJT.
 */
function getBjtModel(value: string): string {
  const v = value.toLowerCase();
  if (v.includes('2n3904')) return 'Q2N3904';
  if (v.includes('2n3906')) return 'Q2N3906';
  if (v.includes('bc547')) return 'QBC547';
  if (v.includes('bc557')) return 'QBC557';
  if (v.includes('mmbt2222')) return 'QMMBT2222A';
  return 'QNPN';
}

/**
 * Generate a SPICE netlist from circuit components.
 * 
 * @param components - Circuit components from the design
 * @param title - Circuit title for the netlist header
 * @param sources - Optional input signal sources
 * @param analysis - Optional analysis directive (.TRAN, .AC, etc.)
 */
export function generateSpiceNetlist(
  components: SpiceComponent[],
  title: string = 'EasyEDA AI Copilot Circuit',
  sources?: SpiceSource[],
  analysis?: SpiceAnalysisOptions,
): string {
  const lines: string[] = [];
  
  // Header
  lines.push(`* ${title}`);
  lines.push(`* Generated by EasyEDA AI Copilot`);
  lines.push(`* ${new Date().toISOString()}`);
  lines.push('');
  
  // Default models
  lines.push('* --- Default Models ---');
  lines.push('.model D D');
  lines.push('.model D1N4148 D (IS=2.52n RS=0.568 N=1.752 CJO=4p M=0.4 TT=20n BV=100 IBV=100u)');
  lines.push('.model DZENER D (IS=2.52n RS=0.568 N=1.752 CJO=4p M=0.4 TT=20n BV=5.1 IBV=5m)');
  lines.push('.model QNPN NPN (IS=1e-15 BF=200 VAF=100)');
  lines.push('.model QPNP PNP (IS=1e-15 BF=150 VAF=100)');
  lines.push('');
  
  // Component netlist
  lines.push('* --- Components ---');
  
  for (const comp of components) {
    const prefix = comp.designator.replace(/\d+$/, '').toUpperCase();
    const val = parseValue(comp.value);
    
    // Sort pins by pin_number to ensure consistent ordering
    const pins = [...comp.pins].sort((a, b) => a.pin_number - b.pin_number);
    
    // Get node names for each pin
    const nodes = pins.map(p => toNode(p.signal_name || `${comp.designator}_pin${p.pin_number}`));
    
    switch (prefix) {
      case 'R': {
        // Resistor: R<name> <node1> <node2> <value>
        if (nodes.length >= 2) {
          lines.push(`${comp.designator} ${nodes[0]} ${nodes[1]} ${val}`);
        }
        break;
      }
      case 'C': {
        // Capacitor: C<name> <node1> <node2> <value>
        if (nodes.length >= 2) {
          lines.push(`${comp.designator} ${nodes[0]} ${nodes[1]} ${val}`);
        }
        break;
      }
      case 'L': {
        // Inductor: L<name> <node1> <node2> <value>
        if (nodes.length >= 2) {
          lines.push(`${comp.designator} ${nodes[0]} ${nodes[1]} ${val}`);
        }
        break;
      }
      case 'D': {
        // Diode: D<name> <anode> <cathode> <model>
        if (nodes.length >= 2) {
          const model = getDiodeModel(comp.value);
          lines.push(`${comp.designator} ${nodes[0]} ${nodes[1]} ${model}`);
        }
        break;
      }
      case 'LED': {
        // LED treated as diode
        if (nodes.length >= 2) {
          lines.push(`${comp.designator} ${nodes[0]} ${nodes[1]} D`);
        }
        break;
      }
      case 'Q': {
        // BJT: Q<name> <collector> <base> <emitter> <model>
        // Standard pin order: B=1, C=2, E=3 (may vary — we sort by pin number)
        if (nodes.length >= 3) {
          const model = getBjtModel(comp.value);
          lines.push(`${comp.designator} ${nodes[0]} ${nodes[1]} ${nodes[2]} ${model}`);
        }
        break;
      }
      case 'U': {
        // IC: model as subcircuit or just annotate
        // For simple ICs with power pins, we annotate the power connections
        const pwrPins = pins.filter(p => 
          p.signal_name.toUpperCase().includes('VCC') || 
          p.signal_name.toUpperCase().includes('VDD')
        );
        const gndPins = pins.filter(p => 
          p.signal_name.toUpperCase().includes('GND') || 
          p.signal_name.toUpperCase().includes('VSS')
        );
        lines.push(`* ${comp.designator} = ${comp.value} (IC)`);
        if (pwrPins.length) {
          for (const pp of pwrPins) {
            lines.push(`*   ${comp.designator} pin ${pp.pin_number} (${pp.name}) -> ${toNode(pp.signal_name)}`);
          }
        }
        if (gndPins.length) {
          for (const gp of gndPins) {
            lines.push(`*   ${comp.designator} pin ${gp.pin_number} (${gp.name}) -> ${toNode(gp.signal_name)}`);
          }
        }
        break;
      }
      case 'X': {
        // Crystal / Oscillator
        if (nodes.length >= 2) {
          lines.push(`${comp.designator} ${nodes[0]} ${nodes[1]} ${val}`);
        }
        break;
      }
      case 'J':
      case 'P': {
        // Connector: annotate only
        lines.push(`* ${comp.designator} = ${comp.value} (Connector)`);
        for (const p of pins) {
          lines.push(`*   pin ${p.pin_number} (${p.name}) -> ${toNode(p.signal_name)}`);
        }
        break;
      }
      case 'SW': {
        // Switch: model as resistor that changes value
        if (nodes.length >= 2) {
          lines.push(`* ${comp.designator} = Switch (${comp.value})`);
          lines.push(`${comp.designator} ${nodes[0]} ${nodes[1]} 0.01`);  // 10mΩ when closed
        }
        break;
      }
      case 'F': {
        // Fuse: model as resistor
        if (nodes.length >= 2) {
          lines.push(`* ${comp.designator} = Fuse (${comp.value})`);
          lines.push(`${comp.designator} ${nodes[0]} ${nodes[1]} 0.001`);  // 1mΩ
        }
        break;
      }
      default: {
        // Generic: annotate
        lines.push(`* ${comp.designator} = ${comp.value} (unknown type: ${prefix})`);
        break;
      }
    }
  }
  
  // Add input sources if provided
  if (sources && sources.length > 0) {
    lines.push('');
    lines.push('* --- Input Sources ---');
    for (const src of sources) {
      const node = toNode(src.signal_name);
      const srcName = src.name.replace(/\s+/g, '_');
      switch (src.type) {
        case 'DC':
          lines.push(`V${srcName} ${node} 0 DC ${src.value}`);
          break;
        case 'SIN':
          lines.push(`V${srcName} ${node} 0 SIN(${src.offset || 0} ${src.value} ${src.frequency || 1000})`);
          break;
        case 'PULSE':
          lines.push(`V${srcName} ${node} 0 PULSE(0 ${src.value} 0 1n 1n ${(src.fill || 50) / 100 / (src.frequency || 1000)} ${1 / (src.frequency || 1000)})`);
          break;
      }
    }
  }
  
  // Add analysis directive
  if (analysis) {
    lines.push('');
    lines.push('* --- Analysis ---');
    switch (analysis.type) {
      case 'transient': {
        const step = (analysis.step_time_ns || 100) / 1e9;
        const end = (analysis.end_time_ns || 60000) / 1e9;
        lines.push(`.tran ${step} ${end}`);
        break;
      }
      case 'ac': {
        const pts = analysis.points_per_decade || 100;
        const start = analysis.start_freq || 10;
        const end = analysis.end_freq || 1e6;
        lines.push(`.ac dec ${pts} ${start} ${end}`);
        break;
      }
      case 'dc': {
        const start = analysis.start_value || 0;
        const end = analysis.end_value || 5;
        const step = analysis.step_value || 0.1;
        lines.push(`.dc ${analysis.source_name || 'V1'} ${start} ${end} ${step}`);
        break;
      }
      case 'op': {
        lines.push('.op');
        break;
      }
    }
  } else {
    // Default: operating point
    lines.push('');
    lines.push('* --- Analysis ---');
    lines.push('.op');
  }
  
  lines.push('');
  lines.push('.end');
  
  return lines.join('\n');
}

/**
 * Export SPICE netlist and trigger browser download.
 */
export function downloadSpiceNetlist(
  components: SpiceComponent[],
  title?: string,
  sources?: SpiceSource[],
  analysis?: SpiceAnalysisOptions,
): void {
  const netlist = generateSpiceNetlist(components, title, sources, analysis);
  const blob = new Blob([netlist], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(title || 'circuit').replace(/\s+/g, '_')}.cir`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
